version: "3.8"

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    command:
      - server
      - /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    ports:
      - "9000:9000"

  store-data:
    image: quay.io/minio/mc
    container_name: client
    depends_on: 
      - minio
    volumes:
      - .:/data
    environment:
      - MC_HOST_MYSTORAGE=http://minioadmin:minioadmin@minio:9000
    entrypoint: >
      /bin/sh -c "
      mc mb MYSTORAGE/demo;
      mc cp /data/README.md MYSTORAGE/demo;
      exit 0;
      "
