name: Build

on:
  workflow_call:

  push:
    branches: [main]

  pull_request:
    branches: [main]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true
env:
  GO_VERSION: "1.24"
jobs:
  build-go:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Setup Go environment
        uses: actions/setup-go@v5.4.0
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build go project
        run: |
          make build
